eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: uav-autha
  datasource:
    url: jdbc:mysql://localhost:3306/db_business?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    ## Redis服务器连接地址
    host: localhost
    ## Redis服务器连接端口
    port: 6379
    timeout: 5000
    ## Redis服务器连接密码（默认为空）
    password: 
    ## Redis服务器连接db
    database: 0
    ## 连接超时时间（毫秒）
    lettuce:
      pool:
        ## 连接池中的最大连接数
        max-idle: 8
        ## 连接池中的最小连接数
        min-idle: 0
        ## 连接池中的最大空闲连接
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dan.danbusiness.mapper.mapper
logging:
  level:
    com.dan.danbusiness.mapper.mapper: DEBUG